name: Trigger Central Pipeline on PR Events

on:
  pull_request:
    types:
      - opened        # Triggered when a PR is created (opened)
      - closed        # Triggered when a PR is merged (closed)
      - synchronize   # Triggered when a PR is updated (new commits)
    branches:
      - main  # Trigger only for PRs against the main branch

jobs:
  trigger_central_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Central Pipeline
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_TOKEN }}  # GitHub Personal Access Token
          repository: Srijan-DevOpsEr/central-Repo  # The central repository where the orchestration pipeline lives
          event-type: pr_event  # Custom event type to trigger the central pipeline
          client-payload: |
            {
              "triggered_by": "${{ github.repository }}",
              "pr_event": "${{ github.event.action }}",  # 'opened', 'synchronize', or 'closed'
              "pr_number": "${{ github.event.pull_request.number }}",
              "commit_sha": "${{ github.sha }}",
              "branch": "${{ github.head_ref }}"
            }
